cd springboot-servicio-config-server;
mvn clean install;
cd ../springboot-servicio-eureka-server;
mvn clean install;
cd ../springboot-servicio-commons;
mvn clean install;
cd ../springboot-servicio-productos;
mvn clean install;
cd ../springboot-servicio-item;	
mvn clean install;
cd ../springboot-servicio-usuarios-commons;
mvn clean install;
cd ../springboot-servicio-usuarios;
mvn clean install;
cd ../springboot-servicio-zuul-server;
mvn clean install;
cd ../springboot-servicio-gateway-server;
mvn clean install;
cd ../springboot-servicio-oauth;
mvn clean install;