spring:
  cloud:
    gateway:
      routes:
      - id: servicio-productos
        uri: lb://servicio-productos
        predicates:
        - Path=/api/productos/**
        #Requisitos para la petición al servicio productos
        #- Header= token, \d+
        #- Header= Content-Type, application/json
        #- Method= GET, POST
        #Si no ponemos el valor, permite cualquier valor para el parámetro "color"
        # Query=color
        #- Query=color, verde
        #- Cookie=color, azul
        filters:
        #porque la ruta está compuesta por dos segementos, api y productos.
        #Si fuese "/productos" pondríamos sólo 1
          - StripPrefix=2
          #EjemploGatewayFilterFactory
          - name: Ejemplo
            args:
              mensaje: Hola, mi mensaje personalizado
              cookieNombre: usuario
              cookieValor: JuanAlejandro 
      - id: servicio-item
        uri: lb://servicio-item
        predicates:
        - Path=/api/item/**
        filters:
        - StripPrefix=2
        #Filtros personalizados de spring que no hace falta programarlos
        - AddRequestHeader=token-request, 1234567890
        - AddResponseHeader=token-response, 0987654321
        #- SetResponseHeader=Content-Type, text/plain
        - AddRequestParameter=nombre, alex
        