spring:
  cloud:
    gateway:
      routes:
      - id: servicio-productos
        uri: lb://servicio-productos
        predicates:
        - Path=/api/productos/**
        filters:
        #porque la ruta está compuesta por dos segementos, api y productos.
        #Si fuese "/productos" pondríamos sólo 1
        - StripPrefix=2
      - id: servicio-item
        uri: lb://servicio-item
        predicates:
        - Path=/api/item/**
        filters:
        - StripPrefix=2